name: E2E Tests

on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Frontend Repository
      uses: actions/checkout@v2

    - name: Checkout E2E Repository
      uses: actions/checkout@v2
      with:
        repository: JoaoVitorSantDrade/cypress-cabeceira
        ref: main 

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.15.0'

    - name: Install Dependencies
      run: |
        npm install

    - name: Run E2E Tests
      uses: cypress-io/github-action@v4
      with:
        command: npm run cypress:run -- --config defaultCommandTimeout=15000
