name: E2E Tests

on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Frontend Repository
      uses: actions/checkout@v2

    - name: Checkout E2E Repository
      uses: actions/checkout@v2
      with:
        repository: JoaoVitorSantDrade/cypress-cabeceira
        ref: main 

    - name: Build and Run E2E Tests Docker Image
      run: |
        docker build -t cypress-e2e-tests:latest .
        docker run cypress-e2e-tests:latest
